## Project-wide Gradle settings.

# Enable the latest Gradle performance features
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Configuration caching is a major performance boost in Gradle 8+
org.gradle.configuration-cache=true
# Ignore minor issues to keep build running
org.gradle.configuration-cache.problems=warn

# Logging and Warnings
org.gradle.logging.level=lifecycle
org.gradle.warning.mode=all

# Android Specifics (required for legacy code accessing resource ids)
android.useAndroidX=true

android.nonFinalResIds=false
android.nonTransitiveRClass=false


##  see twc_credentials_sign.properties

DEBUG_KEY_STORE_FILE= debug.keystore
DEBUG_KEY_STORE_PASSWORD= android
DEBUG_KEY_STORE_ALIAS= androiddebugkey
DEBUG_KEY_STOREY_PASSWORD= android
## DEBUG_API_KEY = AIzaSyBoXfjPGVtk-hxOvmYG7VTGBMTjD8-zFZc

##
## RELEASE_KEY_STORE_FILE = release.keystore
## RELEASE_KEY_STORE_PASSWORD= wsiweather
## RELEASE_KEY_STORE_ALIAS= alias_name
## RELEASE_KEY_STOREY_PASSWORD= wsiweather
## RELEASE_API_KEY = AIzaSyCEJKIfJxwVtfW4bw4OEOgjIeaU02fATTg