pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

// Load Gradle credentials
def propFile = file("twc_credentials_sign.properties")
ext.twc_sign_props = new Properties()
if (propFile.exists()) {
    propFile.withInputStream { twc_sign_props.load(it) }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()

        maven {
            name = 'localMaven'
            url = "libs/maven_repo/"
        }

        flatDir {
            dirs 'libs'
        }

        /*
        maven {
            name = 'weatherRepo'
            url = 'https://android-repo.media.weather.com/MobileMapSDK/Maven'
        }
         */

        // Provide Pangea files required for map tiles.
        maven {
            name = "Pangea"
            credentials {
                // Fallback to environment variables for GitHub Actions
                username = twc_sign_props.PANGEA_MAVEN_USER ?: System.getenv("PANGEA_MAVEN_USER")
                password = twc_sign_props.PANGEA_MAVEN_PWD ?: System.getenv("PANGEA_MAVEN_PWD")
            }
            url = "https://repo.artifacts.weather.com/artifactory/pangea-mobile-kotlin-local"
        }
    }
}
rootProject.name = "all-Routes"
include ':route'
include ':lib_gpx'
include ':lib_data'
