{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wsi.wxdata",
    "module": "wxdata",
    "version": "2.09.0716",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "wxdata-2.09.0716.aar",
          "url": "wxdata-2.09.0716.aar",
          "size": 453752,
          "sha512": "ac0fa6f7df31ff7d5027f805ac52bf4291d18ed2517bfb0e4b79e87dd5e32c0b173afc60da9758872b2d5d7915183dae51259328e065804a26883b8e635d8d73",
          "sha256": "7ec6ceb156a40995660fa8b15ebc2944ee5583ad843c7e56f473d82e1effabb9",
          "sha1": "f04efc9881aef0706bee16d28da6b2b88cad1571",
          "md5": "7c1baf93437316558dbe82503f60231a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "net.danlew",
          "module": "android.joda",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "wxdata-2.09.0716.aar",
          "url": "wxdata-2.09.0716.aar",
          "size": 453752,
          "sha512": "ac0fa6f7df31ff7d5027f805ac52bf4291d18ed2517bfb0e4b79e87dd5e32c0b173afc60da9758872b2d5d7915183dae51259328e065804a26883b8e635d8d73",
          "sha256": "7ec6ceb156a40995660fa8b15ebc2944ee5583ad843c7e56f473d82e1effabb9",
          "sha1": "f04efc9881aef0706bee16d28da6b2b88cad1571",
          "md5": "7c1baf93437316558dbe82503f60231a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wxdata-2.09.0716-javadoc.jar",
          "url": "wxdata-2.09.0716-javadoc.jar",
          "size": 723765,
          "sha512": "19bedb23c02178f03fb559b962594902b01bd7ef354beb6cc0ada761fbd0cdecf4cfe42c75e6dce90d05ec9c30db62ed44cf31e2cc290e4844a1a61a7524f798",
          "sha256": "9a0ee79bc7ca2814cf7f1d04d93f39d3b4596429843562c3038473af44fc2567",
          "sha1": "34590c9641080504ca9d193fbdf30fd9c06c7b01",
          "md5": "0d985d95049b590ef991494f4177ac86"
        }
      ]
    }
  ]
}
