{
  "formatVersion": "1.1",
  "component": {
    "group": "com.weather",
    "module": "mapsdk",
    "version": "2.0.94",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mapsdk-2.0.94.aar",
          "url": "mapsdk-2.0.94.aar",
          "size": 720474,
          "sha512": "d8c7ec5794f67a5785de6e9a83a02f0b85d7ea2b80750694f7f60c68dbc6a1448b17424e2c1e3fdd870e26ca060a6d77290d6bcaf9367b94e9e0eeb0015a7a65",
          "sha256": "a8e997a5b47db3ff80fabf478809b6a2006cbf7bc30a523c5c54688ab1cb8f31",
          "sha1": "d79bd935a1ed9762658c3851c4460977c98594f7",
          "md5": "3ba95c4b8e76f1a3d3e0f55a6220cab7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.weather.pangea.kotlin",
          "module": "pangea-mapbox-android",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "mapsdk-2.0.94.aar",
          "url": "mapsdk-2.0.94.aar",
          "size": 720474,
          "sha512": "d8c7ec5794f67a5785de6e9a83a02f0b85d7ea2b80750694f7f60c68dbc6a1448b17424e2c1e3fdd870e26ca060a6d77290d6bcaf9367b94e9e0eeb0015a7a65",
          "sha256": "a8e997a5b47db3ff80fabf478809b6a2006cbf7bc30a523c5c54688ab1cb8f31",
          "sha1": "d79bd935a1ed9762658c3851c4460977c98594f7",
          "md5": "3ba95c4b8e76f1a3d3e0f55a6220cab7"
        }
      ]
    }
  ]
}
